title: weak self podcast
author: weakselfpodcast
description: > # this means to ignore newlines until "show_exerpts:"
  在 iOS 開發圈打滾的台灣工程師，專為 Apple/iOS 開發者而製作的 Podcast。主講人一三、波肥。
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /episodes/:title
texture:
  title: weak self podcast
  tagline: 在 iOS 開發圈打滾的台灣工程師，專為 Apple/iOS 開發者而製作的 Podcast。主講人一三、波肥。
  date_format: "%Y/%m/%d"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: weak_self
    rss: rss
 
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed